# Default values for open5gs-epc-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

open5gs:
  image:
    repository: registry.gitlab.com/infinitydon/registry/open5gs-aio
    pullPolicy: IfNotPresent
    tag: v2.5.6

webui:
  image:
    repository: registry.gitlab.com/infinitydon/registry/open5gs-webui
    pullPolicy: IfNotPresent
    tag: "v2.5.6"
  svc: 123.123.123.11

ueImport:
  image:
    repository: free5gmano/nextepc-mongodb
    pullPolicy: IfNotPresent
    tag: "latest"

simulator:  
   ue1:
     imsi: "208930000000031"
     imei: "356938035643803"
     imeiSv: "4370816125816151"
     op: "8e27b6af0e692e750f32667a3b14605d"
     secKey: "8baf473f2f8fd09487cccbd7097c6862"
     sst: "1"
     sd: "1"
   ue2:
     imsi: "208930000000032"
     imei: "356938035643803"
     imeiSv: "4370816125816151"
     op: "8e27b6af0e692e750f32667a3b14605d"
     secKey: "8baf473f2f8fd09487cccbd7097c6862"
     sst: "1"
     sd: "1"     

dnn: internet

k8swait:
  repository: groundnuty/k8s-wait-for
  tag: v1.6
  pullPolicy: IfNotPresent  

k8s:
  interface: eth0

amf:
  mcc: 208
  mnc: 93
  tac: 7
  networkName: Open5GS
  ngapInt: eth0
  svc: 123.123.123.1

smf:
  N4Int: eth0
  upfPublicIP: 123.123.123.2

nssf:
  sst: "1"
  sd: "1" 
  svc: 123.123.123.5

prometheus:
  nodeExporter:
     repository: quay.io/prometheus/node-exporter
     tag: v1.3.1
     pullPolicy: IfNotPresent

mongodb:
  svc: 123.123.123.3
nrf:
  svc: 123.123.123.4
udm:
  svc: 123.123.123.6
pcf:
  svc: 123.123.123.7
bsf:
  svc: 123.123.123.8
ausf:
  svc: 123.123.123.9
udr:
  svc: 123.123.123.10
