---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-amf
  annotations:
    loxilb.io/probetype : "ping"
    loxilb.io/lbmode : "fullnat"
    loxilb.io/staticIP: {{ .Values.amf.svc }}
  labels:
    epc-mode: amf
spec:
  type: LoadBalancer
  loadBalancerClass: loxilb.io/loxilb
  selector:
    epc-mode: amf
  ports:
    - protocol: SCTP
      name: amf-ngap
      port: 38412
      nodePort: 32670
      targetPort: 38412
    - protocol: TCP
      name: amf-sbi
      port: 7777
      targetPort: 7777
    - protocol: TCP
      name: amf-80-tcp
      port: 80   
      targetPort: 80      
---  
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-amf-deployment
  labels:
    epc-mode: amf
spec:
  replicas: 2
  selector:
    matchLabels:
      epc-mode: amf
  template:
    metadata:
      labels:
        epc-mode: amf
        epc-prom: enabled
    spec:
      serviceAccountName: {{ .Release.Name }}-k8s-wait-for
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              epc-mode: amf
      initContainers:    
      - name: wait-for-nrf
        image: "{{ .Values.k8swait.repository }}:{{ .Values.k8swait.tag }}"
        imagePullPolicy: {{ .Values.k8swait.pullPolicy }}
        args:
          - "pod"
          - "-lepc-mode=nrf"
      containers:
        - name: amf
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          ports:
          - containerPort: 9090
            name: prom
            protocol: TCP
          command: ["/bin/sh", "-c"]
          args:
          - apt-get update;
            apt-get install tcpdump iputils-ping -y;
            open5gs-amfd -c /open5gs/config-map/amf.yaml;          
          securityContext:
             capabilities:
               add:
               - NET_ADMIN
          volumeMounts:
          - name: {{ .Release.Name }}-amf-config
            mountPath: /open5gs/config-map/amf.yaml
            subPath: "amf.yaml" 
      volumes:
        - name: {{ .Release.Name }}-amf-config
          configMap:
            name: {{ .Release.Name }}-amf-config
