apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-smf
  labels:
    epc-mode: smf
  annotations:
    loxilb.io/probetype : "ping"
    loxilb.io/lbmode : "fullnat"
    loxilb.io/staticIP: "123.123.123.2"
spec:
  type: LoadBalancer
  loadBalancerClass: loxilb.io/loxilb
  selector:
    epc-mode: smf
  ports:
    - protocol: UDP
      name: smf-gtpc
      port: 2123
      targetPort: 2123
    - protocol: UDP
      name: smf-pfcp
      port: 8805
      targetPort: 8805
    - protocol: TCP
      name: smf-frdi-tcp
      port: 3868 
      targetPort: 3868 
    - protocol: SCTP
      name: smf-frdi-sctp
      port: 3868 
      targetPort: 3868 
    - protocol: TCP
      name: smf-sbi
      port: 7777
      targetPort: 7777
    - protocol: UDP
      name: smf-gtpu
      port: 2152
      targetPort: 2152
    - protocol: TCP
      name: smf-9090-tcp
      port: 9090
      targetPort: 9090
    - protocol: TCP
      name: smf-80-tcp
      port: 80 
      targetPort: 80  
---  
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-smf-deployment
  labels:
    epc-mode: smf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: smf
  template:
    metadata:
      # annotations:
      #    k8s.v1.cni.cncf.io/networks: '[
      #            { "name": "core5g-def",
      #              "ips": [ {{- cat .Values.smf.multusN4IP "/" .Values.smf.multusN4NetworkMask | nospace | quote }} ] }
      #    ]'      
      labels:
        epc-mode: smf
        epc-prom: enabled
    spec:
      serviceAccountName: {{ .Release.Name }}-k8s-wait-for
      initContainers:    
      - name: wait-for-nrf
        image: "{{ .Values.k8swait.repository }}:{{ .Values.k8swait.tag }}"
        imagePullPolicy: {{ .Values.k8swait.pullPolicy }}
        args:
          - "pod"
          - "-lepc-mode=nrf"            
      containers:
      - name: smf
        image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
        imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
        ports:
        - containerPort: 9090
          name: prom
          protocol: TCP       
        command: ["/bin/sh", "-c"]
        args:
        - apt-get update;
          apt-get install iputils-ping iperf3 -y;
          open5gs-smfd -c /open5gs/config-map/smf.yaml;
        volumeMounts:
          - name: {{ .Release.Name }}-smf-config
            mountPath: /open5gs/config-map/smf.yaml
            subPath: "smf.yaml"          
        securityContext:
           capabilities:
             add:
             - NET_ADMIN 
      volumes:
        - name: {{ .Release.Name }}-smf-config
          configMap:
            name: {{ .Release.Name }}-smf-config                
